[build]
builder = "RAILPACK"
buildCommand = "npm run build"

[deploy]
startCommand = "npx prisma db push && npm run prisma:seed && npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
