[build]
builder = "RAILPACK"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
preDeployCommand = "npm run prisma:deploy && npm run prisma:seed"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
